import 'package:hive/hive.dart';

/// A single flashcard: a question on the front, an answer on the back.
///
/// NOTE: The Hive adapter below is hand-written (not generated by
/// build_runner) so the app compiles and runs immediately.
class FlashcardModel extends HiveObject {
  String id;
  String question;
  String answer;
  String category; // optional grouping, e.g. "Biology", "General"
  DateTime createdAt;

  FlashcardModel({
    required this.id,
    required this.question,
    required this.answer,
    this.category = 'General',
    required this.createdAt,
  });
}

/// Hand-written Hive TypeAdapter for [FlashcardModel].
class FlashcardModelAdapter extends TypeAdapter<FlashcardModel> {
  @override
  final int typeId = 1;

  @override
  FlashcardModel read(BinaryReader reader) {
    final numOfFields = reader.readByte();
    final fields = <int, dynamic>{
      for (int i = 0; i < numOfFields; i++) reader.readByte(): reader.read(),
    };
    return FlashcardModel(
      id: fields[0] as String,
      question: fields[1] as String,
      answer: fields[2] as String,
      category: fields[3] as String? ?? 'General',
      createdAt: fields[4] as DateTime,
    );
  }

  @override
  void write(BinaryWriter writer, FlashcardModel obj) {
    writer
      ..writeByte(5)
      ..writeByte(0)
      ..write(obj.id)
      ..writeByte(1)
      ..write(obj.question)
      ..writeByte(2)
      ..write(obj.answer)
      ..writeByte(3)
      ..write(obj.category)
      ..writeByte(4)
      ..write(obj.createdAt);
  }
}
